version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nestdb
      POSTGRES_USER: mario
      POSTGRES_PASSWORD: mariopassword
    ports:
      - '5499:5432'
